---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: Check Running config Interfaces
    raw:
       - conf t
       - int {{ interface }}
       - do show run int {{ interface }}