---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: Check Running config Interfaces
    ios_config:
      lines:
       - do show run int {{ interface }}
      parents: interface {{ interface }}