---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: Check System Device
    ios_command:
      commands: show system
      wait_for:
        - result[0] contains Description
      register: des
  
   - debug:
      des_device="{{ des.stdout }}"