---
- name: Check uptime Demo..!!!
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:

  - name: Command Uptime
    ios_command:
      commands: show system
    register: system
  - debug: msg="{{ system.stdout }}"
