---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:

  - name: Check System Device
    ios_command:
      commands: show system
      stdout_lines: no
      wait_for:
        - result[0] contains Description
